# fly.toml app configuration file generated for adat on 2023-06-17T17:45:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "adat"
primary_region = "sea"

[env]
  PORT = "8080"
  DATABASE_URL = "file:/data/prices.db"

[[mounts]]
  source = "jamsqlite"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
