name: Main

on:
  push:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          run_install: true

  typecheck:
    needs: install
    runs-on: ubuntu-latest
    steps: 
      - run: pnpm run check

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: pnpm run test --run
  
