name: Main

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          run_install: true
  
      - name: typecheck
        run: pnpm run check
  
      - name: test run
        run: pnpm run test --run
  
